"""on_delete=cascade

Revision ID: c1639b1169bf
Revises: faae0bdaeea2
Create Date: 2024-05-28 19:39:13.672529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1639b1169bf"
down_revision: Union[str, None] = "faae0bdaeea2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payment_task_id_fkey", "payment", type_="foreignkey")
    op.drop_constraint("payment_user_id_fkey", "payment", type_="foreignkey")
    op.create_foreign_key(
        None, "payment", "account", ["user_id"], ["public_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "payment", "task", ["task_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("task_user_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key(
        None, "task", "account", ["user_id"], ["public_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.create_foreign_key(
        "task_user_id_fkey", "task", "account", ["user_id"], ["public_id"]
    )
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.create_foreign_key(
        "payment_user_id_fkey", "payment", "account", ["user_id"], ["public_id"]
    )
    op.create_foreign_key(
        "payment_task_id_fkey", "payment", "task", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
