"""user_public_id

Revision ID: 0b64126077c1
Revises: dea101184bd1
Create Date: 2024-05-29 11:37:59.640117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b64126077c1"
down_revision: Union[str, None] = "dea101184bd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("user_public_id", sa.UUID(), nullable=False))
    op.drop_constraint("account_public_id_key", "account", type_="unique")
    op.create_unique_constraint(None, "account", ["user_public_id"])
    op.drop_column("account", "public_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column("public_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "account", type_="unique")
    op.create_unique_constraint("account_public_id_key", "account", ["public_id"])
    op.drop_column("account", "user_public_id")
    # ### end Alembic commands ###
