"""on_delete=cascade

Revision ID: dea101184bd1
Revises: b1833f62eee9
Create Date: 2024-05-28 19:40:17.092218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dea101184bd1"
down_revision: Union[str, None] = "b1833f62eee9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("auth_user_id_fkey", "auth", type_="foreignkey")
    op.create_foreign_key(
        None, "auth", "account", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "auth", type_="foreignkey")
    op.create_foreign_key("auth_user_id_fkey", "auth", "account", ["user_id"], ["id"])
    # ### end Alembic commands ###
